-- MySQL Script generated by MySQL Workbench
-- Sun Dec  5 23:14:02 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`direccion` (
  `iddireccion` INT NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(50) NULL,
  `municipio` VARCHAR(50) NULL,
  `colonia` VARCHAR(70) NULL,
  `calle` VARCHAR(60) NULL,
  `numeroExterior` INT(5) NULL,
  `numeroInterior` VARCHAR(7) NULL,
  `codigoPostal` INT(10) NULL,
  `referencias` VARCHAR(100) NULL,
  `contacto` INT(14) NULL,
  `indicaciones` VARCHAR(180) NULL,
  PRIMARY KEY (`iddireccion`))
ENGINE = InnoDB
COMMENT = '		';


-- -----------------------------------------------------
-- Table `mydb`.`metodoPago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`metodoPago` (
  `idmetodoPago` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  `metodoPagocol` VARCHAR(45) NULL,
  PRIMARY KEY (`idmetodoPago`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clientes` (
  `idclientes` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `apellido` VARCHAR(100) NULL,
  `correo` VARCHAR(80) NULL,
  `telefono` INT(14) NULL,
  `edad` INT(3) NULL,
  `contraseña` VARCHAR(60) NULL,
  `nombreUsuario` VARCHAR(45) NULL,
  `fechaNacimiento` DATE NULL,
  `direccion_iddireccion` INT NOT NULL,
  `metodoPago_idmetodoPago` INT NOT NULL,
  PRIMARY KEY (`idclientes`, `direccion_iddireccion`, `metodoPago_idmetodoPago`),
  CONSTRAINT `fk_clientes_direccion`
    FOREIGN KEY (`direccion_iddireccion`)
    REFERENCES `mydb`.`direccion` (`iddireccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_clientes_metodoPago1`
    FOREIGN KEY (`metodoPago_idmetodoPago`)
    REFERENCES `mydb`.`metodoPago` (`idmetodoPago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_clientes_direccion_idx` ON `mydb`.`clientes` (`direccion_iddireccion` ASC) VISIBLE;

CREATE INDEX `fk_clientes_metodoPago1_idx` ON `mydb`.`clientes` (`metodoPago_idmetodoPago` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`comics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comics` (
  `idcomics` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NULL,
  `descripcion` VARCHAR(150) NULL,
  `imagen` VARCHAR(1000) NULL,
  `precioCompra` INT NULL,
  `precioVenta` INT NULL,
  `paginas` INT NULL,
  `existencia` INT NULL,
  PRIMARY KEY (`idcomics`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`genero` (
  `idgenero` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `edades` INT NULL,
  PRIMARY KEY (`idgenero`))
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `mydb`.`autores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`autores` (
  `idautores` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(80) NULL,
  `apellidos` VARCHAR(80) NULL,
  PRIMARY KEY (`idautores`))
ENGINE = InnoDB
COMMENT = '		';


-- -----------------------------------------------------
-- Table `mydb`.`comics_has_autores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comics_has_autores` (
  `comics_idcomics` INT NOT NULL,
  `autores_idautores` INT NOT NULL,
  PRIMARY KEY (`comics_idcomics`, `autores_idautores`),
  CONSTRAINT `fk_comics_has_autores_comics1`
    FOREIGN KEY (`comics_idcomics`)
    REFERENCES `mydb`.`comics` (`idcomics`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comics_has_autores_autores1`
    FOREIGN KEY (`autores_idautores`)
    REFERENCES `mydb`.`autores` (`idautores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_comics_has_autores_autores1_idx` ON `mydb`.`comics_has_autores` (`autores_idautores` ASC) VISIBLE;

CREATE INDEX `fk_comics_has_autores_comics1_idx` ON `mydb`.`comics_has_autores` (`comics_idcomics` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`comics_has_genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comics_has_genero` (
  `comics_idcomics` INT NOT NULL,
  `genero_idgenero` INT NOT NULL,
  PRIMARY KEY (`comics_idcomics`, `genero_idgenero`),
  CONSTRAINT `fk_comics_has_genero_comics1`
    FOREIGN KEY (`comics_idcomics`)
    REFERENCES `mydb`.`comics` (`idcomics`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comics_has_genero_genero1`
    FOREIGN KEY (`genero_idgenero`)
    REFERENCES `mydb`.`genero` (`idgenero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_comics_has_genero_genero1_idx` ON `mydb`.`comics_has_genero` (`genero_idgenero` ASC) VISIBLE;

CREATE INDEX `fk_comics_has_genero_comics1_idx` ON `mydb`.`comics_has_genero` (`comics_idcomics` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`figuras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`figuras` (
  `idfiguras` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `imagen` VARCHAR(45) NULL,
  `precioCompra` VARCHAR(45) NULL,
  `precioVenta` VARCHAR(45) NULL,
  `existencia` VARCHAR(45) NULL,
  PRIMARY KEY (`idfiguras`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `mydb`.`tipoPrenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipoPrenda` (
  `idtipoPrenda` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(80) NULL,
  `descripcion` VARCHAR(150) NULL,
  `genero` VARCHAR(10) NULL,
  PRIMARY KEY (`idtipoPrenda`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`prendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`prendas` (
  `idprendas` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `descipcion` VARCHAR(45) NULL,
  `medidas` VARCHAR(45) NULL,
  `precioCompra` INT NULL,
  `precioVenta` INT NULL,
  `tipoPrenda_idtipoPrenda` INT NOT NULL,
  PRIMARY KEY (`idprendas`),
  CONSTRAINT `fk_prendas_tipoPrenda1`
    FOREIGN KEY (`tipoPrenda_idtipoPrenda`)
    REFERENCES `mydb`.`tipoPrenda` (`idtipoPrenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_prendas_tipoPrenda1_idx` ON `mydb`.`prendas` (`tipoPrenda_idtipoPrenda` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`carrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`carrito` (
  `idcarrito` INT NOT NULL AUTO_INCREMENT,
  `fechaAgregado` DATE NULL,
  `montoTotal` INT NULL,
  `montoEnvio` INT NULL,
  PRIMARY KEY (`idcarrito`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`favoritos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`favoritos` (
  `idfavoritos` INT NOT NULL AUTO_INCREMENT,
  `fechaAgregado` DATE NULL,
  `comics_idcomics` INT NOT NULL,
  `figuras_idfiguras` INT NOT NULL,
  `prendas_idprendas` INT NOT NULL,
  PRIMARY KEY (`idfavoritos`, `prendas_idprendas`),
  CONSTRAINT `fk_favoritos_comics1`
    FOREIGN KEY (`comics_idcomics`)
    REFERENCES `mydb`.`comics` (`idcomics`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_favoritos_figuras1`
    FOREIGN KEY (`figuras_idfiguras`)
    REFERENCES `mydb`.`figuras` (`idfiguras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_favoritos_prendas1`
    FOREIGN KEY (`prendas_idprendas`)
    REFERENCES `mydb`.`prendas` (`idprendas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_favoritos_comics1_idx` ON `mydb`.`favoritos` (`comics_idcomics` ASC) VISIBLE;

CREATE INDEX `fk_favoritos_figuras1_idx` ON `mydb`.`favoritos` (`figuras_idfiguras` ASC) VISIBLE;

CREATE INDEX `fk_favoritos_prendas1_idx` ON `mydb`.`favoritos` (`prendas_idprendas` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pedido` (
  `idpedido` INT NOT NULL AUTO_INCREMENT,
  `cantidad` VARCHAR(45) NULL,
  `fechaHora` VARCHAR(45) NULL,
  `metodoPago_idmetodoPago` INT NOT NULL,
  PRIMARY KEY (`idpedido`),
  CONSTRAINT `fk_pedido_metodoPago1`
    FOREIGN KEY (`metodoPago_idmetodoPago`)
    REFERENCES `mydb`.`metodoPago` (`idmetodoPago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_pedido_metodoPago1_idx` ON `mydb`.`pedido` (`metodoPago_idmetodoPago` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`clientes_has_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clientes_has_pedido` (
  `clientes_idclientes` INT NOT NULL,
  `clientes_direccion_iddireccion` INT NOT NULL,
  `pedido_idpedido` INT NOT NULL,
  PRIMARY KEY (`clientes_idclientes`, `clientes_direccion_iddireccion`, `pedido_idpedido`),
  CONSTRAINT `fk_clientes_has_pedido_clientes1`
    FOREIGN KEY (`clientes_idclientes` , `clientes_direccion_iddireccion`)
    REFERENCES `mydb`.`clientes` (`idclientes` , `direccion_iddireccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_clientes_has_pedido_pedido1`
    FOREIGN KEY (`pedido_idpedido`)
    REFERENCES `mydb`.`pedido` (`idpedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_clientes_has_pedido_pedido1_idx` ON `mydb`.`clientes_has_pedido` (`pedido_idpedido` ASC) VISIBLE;

CREATE INDEX `fk_clientes_has_pedido_clientes1_idx` ON `mydb`.`clientes_has_pedido` (`clientes_idclientes` ASC, `clientes_direccion_iddireccion` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`comics_has_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comics_has_pedido` (
  `comics_idcomics` INT NOT NULL,
  `pedido_idpedido` INT NOT NULL,
  PRIMARY KEY (`comics_idcomics`, `pedido_idpedido`),
  CONSTRAINT `fk_comics_has_pedido_comics1`
    FOREIGN KEY (`comics_idcomics`)
    REFERENCES `mydb`.`comics` (`idcomics`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comics_has_pedido_pedido1`
    FOREIGN KEY (`pedido_idpedido`)
    REFERENCES `mydb`.`pedido` (`idpedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_comics_has_pedido_pedido1_idx` ON `mydb`.`comics_has_pedido` (`pedido_idpedido` ASC) VISIBLE;

CREATE INDEX `fk_comics_has_pedido_comics1_idx` ON `mydb`.`comics_has_pedido` (`comics_idcomics` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`figuras_has_carrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`figuras_has_carrito` (
  `figuras_idfiguras` INT NOT NULL,
  `carrito_idcarrito` INT NOT NULL,
  PRIMARY KEY (`figuras_idfiguras`, `carrito_idcarrito`))
ENGINE = MyISAM;

CREATE INDEX `fk_figuras_has_carrito_carrito1_idx` ON `mydb`.`figuras_has_carrito` (`carrito_idcarrito` ASC) VISIBLE;

CREATE INDEX `fk_figuras_has_carrito_figuras1_idx` ON `mydb`.`figuras_has_carrito` (`figuras_idfiguras` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`carrito_has_comics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`carrito_has_comics` (
  `carrito_idcarrito` INT NOT NULL,
  `comics_idcomics` INT NOT NULL,
  PRIMARY KEY (`carrito_idcarrito`, `comics_idcomics`),
  CONSTRAINT `fk_carrito_has_comics_carrito1`
    FOREIGN KEY (`carrito_idcarrito`)
    REFERENCES `mydb`.`carrito` (`idcarrito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carrito_has_comics_comics1`
    FOREIGN KEY (`comics_idcomics`)
    REFERENCES `mydb`.`comics` (`idcomics`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_carrito_has_comics_comics1_idx` ON `mydb`.`carrito_has_comics` (`comics_idcomics` ASC) VISIBLE;

CREATE INDEX `fk_carrito_has_comics_carrito1_idx` ON `mydb`.`carrito_has_comics` (`carrito_idcarrito` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`carrito_has_prendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`carrito_has_prendas` (
  `carrito_idcarrito` INT NOT NULL,
  `prendas_idprendas` INT NOT NULL,
  PRIMARY KEY (`carrito_idcarrito`, `prendas_idprendas`),
  CONSTRAINT `fk_carrito_has_prendas_carrito1`
    FOREIGN KEY (`carrito_idcarrito`)
    REFERENCES `mydb`.`carrito` (`idcarrito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carrito_has_prendas_prendas1`
    FOREIGN KEY (`prendas_idprendas`)
    REFERENCES `mydb`.`prendas` (`idprendas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_carrito_has_prendas_prendas1_idx` ON `mydb`.`carrito_has_prendas` (`prendas_idprendas` ASC) VISIBLE;

CREATE INDEX `fk_carrito_has_prendas_carrito1_idx` ON `mydb`.`carrito_has_prendas` (`carrito_idcarrito` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
